---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ci
rules:
- apiGroups: [""]
  resources:
  - services
  - configmaps
  - secrets
  - endpoints
  - persistentvolumeclaims
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: ["extensions"]
  resources:
  - ingresses
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: ["extensions", "apps"]
  resources:
  - deployments
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources:
  - statefulsets
  - replicasets
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["get", "list", "create", "update", "patch", "delete"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ci
subjects:
- kind: ServiceAccount
  name: ci
roleRef:
  kind: Role
  name: ci
  apiGroup: rbac.authorization.k8s.io
