version: '2'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        container_version: ${IMAGE_VERSION}
    ports:
      - "8080:8080"
    environment:
      NGINX_PORT: 8080
    image: docker-registry.labs.intellij.net/ksk/starter-kit:${IMAGE_VERSION}
